### ISSUE TITLE
document audit management commands

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/cityhallmonitor#120]
I just ran `./manage.py audit_dc` against my local database, which was primed by a very recent dump of production data.

I was greeted with a large list of `ERROR source not found in db` messages before I cancelled the audit.

Please add some information, possibly simply as a docstring at the top of the management command source files, explaining how one might use these commands, what sort of output to expect, etc.

If the messages I was getting were noise, we should see if we can suppress them, but if not, at least provide a way for someone running the command to distinguish them from more meaningful information.

**Comment by jywsn** [comment]
These management commands are no longer relevant with the new storage scheme.  You can remover them.  Old info is on them is in the repo wiki.
