### ISSUE TITLE
Different results header language for default document list

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/cityhallmonitor#124]
At the moment, when you load the front page of CHM (development branch) you see a message like "We found 152 results matching in the last 30 days."

This is gramatically incorrect because there is no search term in between "matching" and "in the last 30 days." -- we should show a different message which both doesn't have this problem, but more importantly, makes clear that we're showing a default query.

**Comment by hbillings** [comment]
Moved "matching" to be part of the keyword var, so it's no longer grammatically incorrect. We don't currently have a way to tell whether we're showing the default query or just a query with a time element and no keywords.

**Comment by JoeGermuska** [comment]
I don't think there's a critical difference between the default query and any other query with no keywords, so I implemented a switch on the presence of `query` (aka keywords).
