### ISSUE TITLE
Implement sort by relevance vs sort by date in client search UI

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/cityhallmonitor#125]
right now the "Sort by" links don't function. They should correctly be styled to match whatever sort is currently active on any displayed results, and the non-active option(s) should be links which resort the current search result, optimally using javascript instead of a fresh query to the database.

Also, at this time, the javascript is always sorting results by date instead of honoring the order in which they come back and sorting only as necessary.

Note that the "default" search for non-routine documents in the last 30 days has no text component, and so can't really be ranked for relevance. How should we handle that? (somewhat related to #124)

**Comment by hbillings** [comment]
You can see the WIP version of this in the `sort-results` branch. I refactored a bunch of javascript (it's still messy) so it's not all happening in the AJAX call — should be easier to pick apart and modify that way, as well as to display new results via JS instead of a different DB query.
