### ISSUE TITLE
Redesign search results

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#131]
Put less emphasis on title
Show thumbnails of first three pages
Remove "Read" and "Download" buttons

**Comment by JoeGermuska** [comment]
I love the thumbnails. I'm a little nervous that it appears that there are only three pages. Especially because sometimes there are only 2, that makes it look a little more like it's a complete list.

I'm also Not sure there's enough action cue without the 'read' button but we can talk about it with other folks.

**Comment by hbillings** [comment]
I agree that the thumbnails are a bit misleading. It would be really nice to be able to have a total page count on there (especially since my ugly hack to hide the broken image that occurs when a matter only has two pages relies on javascript timeouts).

I think we do need to add a call to action back, but perhaps just a "read" link instead of a button (a la the download link in the previous iteration).

**Comment by JoeGermuska** [comment]
I added a `page_count` attribute to `MatterAttachment` -- to use it locally, you'll have to `python manage.py migrate` and then `python manage.py set_page_counts --count 100`

`set_page_counts` will update `page_count` for all of your documents if you don't specify `--count`, but it would be slow. It seems to be going faster on staging, so maybe I'll make another database dump. One could also run it for 1000 or so and then do `echo 'update cityhallmonitor_matterattachment set page_count = 2 where page_count is null' | python manage.py dbshell`

So now we could both consult that value to preempt showing the third image and waiting for it to 404, and we could also show some "ellipsis" like visual when there are more pages than are shown (and maybe just put _(n pages)_ in the results?

**Comment by hbillings** [comment]
YAY!! ^_^
