### ISSUE TITLE
Add introductory material to page topper

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#133]
"Typical interesting documents" (yet to be identified)
Example search result with friendly explainer text

**Comment by JoeGermuska** [comment]
assigned to heather to implement visual/lorem ipsum design

**Comment by hbillings** [comment]
I've done what I can with this prior to redesigning the search results themselves. I'll take another pass at this admittedly rough work once I get the search results looking happier. Back to you in the studio, Joe!
