### ISSUE TITLE
"Boring stuff" doesn't get included in result display

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#146]
even when the "ignore" box is unchecked. It does, however, get reflected in the total documents found. For example, searching for "permit" in the last month results in "We found 8 results matching permit in the last 30 days" but only one result being displayed.

**Comment by JoeGermuska** [comment]
I can't reproduce this. I just tried permit and got different counts, but the number of displayed documents matches the results count as I'd expect.

**Comment by hbillings** [comment]
Yeah, it looks right now! Coolio.
