### ISSUE TITLE
search results sort order

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/cityhallmonitor#19]
Are results from DocumentCloud returned in a certain order (e.g. relevance)?  Is there some field in that data that we should be sorting by?  My first thought was to sort them by the updated_at field, but we are grouping them by matter, so I don't know.

**Comment by scott2b** [comment]
Per Ted Han:

The sort things we've got are

* relevance (to the search query
…question)
* uploaded date
* title (alpha sort)
* source
* length (page count
