### ISSUE TITLE
easier way to drill into search results

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/cityhallmonitor#29]
Arguably, the summaries could be suppressed on first display of the list, as they rarely seem helpful.

If we know any attributes of the results to support faceting, a sidebar of facet properties would be useful.

Pagination, maybe?

What is the rationale for ordering results? Is it just passing through the order from Document Cloud? That's probably fine, although it's a little puzzling.

**Comment by scott2b** [comment]
I think we are moving in a good direction re: organizing search results and making them useful. Closing this as answered for now.
