### ISSUE TITLE
back button loses search results

### ISSUE THREAD

**Issue by JoeGermuska** [NUKnightLab/cityhallmonitor#33]
Easy fix: open documents in a new window.

More sophisticated: can we use the browser's history mechanism to store search results? It seems that the maximum size for a 'state' object is not formalized, but here's some info: http://stackoverflow.com/questions/6460377/html5-history-api-what-is-the-max-size-the-state-object-can-be

**Comment by scott2b** [comment]
Did we decide to open documents in a new tab at least for this iteration?

**Comment by jywsn** [comment]
User will command-click to open in a new tab.  The default click behavior will load the document viewer in an overlay/modal/whatzit.

**Comment by scott2b** [comment]
This is a good solution. @hbillings, do we have a standard modal library that should be used for this?

**Comment by hbillings** [comment]
Foundation includes [a modal component](http://foundation.zurb.com/docs/components/reveal.html). I haven't styled it for Purpleline, so it's not on the Purpleline page, but including cdn.knightlab.com/libs/purpleline/latest/js/foundation.reveal.js should work.

**Comment by scott2b** [comment]
New modal approach to doc display obsoletes this.
