### ISSUE TITLE
Unsubscribe mechanism explanation

### ISSUE THREAD

**Issue by jywsn** [NUKnightLab/cityhallmonitor#38]
When someone subscribes to a search, we create a Subscription record, which contains fields for a query, an email address, and the time we last searched for results.

All subscription emails (including the initial one that notifies the user of their new subscription) contain an "Unsubscribe" link.  This link contains a `sid` parameter that is composed of the Subscription record id and an md5 hash of the email address.  See here:  

https://github.com/NUKnightLab/cityhallmonitor/blob/master/cityhallmonitor/views.py#L15-L18

When someone clicks on that link to unsubscribe, we verify as follows:  take the `sid` parameter and split the id from the hash, look up the Subscription record by that id, make a `sid` from the info in the Subscription record and compare it to the `sid` parameter.

**Comment by scott2b** [comment]
This looks informational and possibly historical. @jywsn is there an issue here? Can this be closed?

**Comment by jywsn** [comment]
It is informational.  You can close it if you like.
