### ISSUE TITLE
Come up with better examples

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#40]
The search examples are silly things from the mockups.

**Comment by jywsn** [comment]
here's an interesting one:  "sale of city-owned property"

**Comment by scott2b** [comment]
@jywsn 's suggestion is a good one. Do we need more? Can this be put in the UI and closed?

**Comment by hbillings** [comment]
At least one more would be good.

**Comment by jywsn** [comment]
Maybe "O'Hare noise"

**Comment by jywsn** [comment]
Also, both of these suggestions (above) are better if quoted, e.g `"sale of city-owned property"` not `sale of city-owned property`

**Comment by scott2b** [comment]
My current best suggestions are “Inspector General’s report” (174 results) and “school zoning reclassification” (254 results). But I'm not necessarily attached to those -- just throwing out ideas.

**Comment by scott2b** [comment]
Also :+1: for O'Hare noise

**Comment by scott2b** [comment]
And a random idea: if we got at least 10 or 20 of these, it would be fun to implement it to serve up 2 random examples when the page is loaded.

**Comment by hbillings** [comment]
I like all of these but am going with "school zoning reclassification" for now.
