### ISSUE TITLE
Wireframe summary of search results

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#42]
We talked about having a summary of search results like, "Your search returned XX matters" and possibly pulling out other related info. @jywsn and @scott2b, do you recall details about what sorts of things the summaries might entail? I didn't note them but it would be helpful to have a broad idea for wireframing.

**Comment by jywsn** [comment]
I'm not sure what you mean by "summaries".  We talked about facets and filters.... what would a "summary" be?

**Comment by scott2b** [comment]
For current work: assume count by MatterType and count by Matter status.

**Comment by hbillings** [comment]
Will upload screenshot to basecamp when I'm on a better internet connection.
