### ISSUE TITLE
Wireframe filters & facets

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#43]
Facets: 
- Matter type
- Status
- Dates introduced/assed
- Sponsor (potentially)

Filters:
TBD

**Comment by jywsn** [comment]
Maybe add the "MatterBody" (e.g. "Committee on Pedestrian and Traffic Safety") to one of these two categories.  It could be a facet, because matter-to-body is a 1-to-1 relationship.  The body name is not currently stored in the document data on DC, but it could be.
