### ISSUE TITLE
Make search filters work

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#44]
The UI is there, but they don't currently filter search terms. I'm not sure how we want to populate the values for these, whether dynamically or from a static list. With a hardcoded list of values, we might run the risk of missing new values if they are added. (The most obvious one here is dates.)

**Comment by scott2b** [comment]
Obsoleted by #57 and decision to only use date-range filtering

**Comment by hbillings** [comment]
Date filters still need to be hooked up to work...

**Comment by scott2b** [comment]
yes, that is #57
