### ISSUE TITLE
Build out email management UI

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#47]

**Comment by scott2b** [comment]
What is the current state of "email management". My only concerns are that we have double-opt in and easy unsubscribe. Given the implementation of those things I'd prefer to see a more involved UI tabled for next milestone.

**Comment by jywsn** [comment]
Assigning this to myself for now.  Will implement the basic mechanism for double opt-in.

**Comment by hbillings** [comment]
might be helpful for future reference: https://basecamp.com/1937751/projects/9758052/uploads/26762665?enlarge=186157207#attachment_186157207

**Comment by jywsn** [comment]
Basic mechanisms are working.  Until the real front-end is ready, you can make a subscription by going to:  https://cityhallmonitor.knilab.com/subscribe?email=XXX&query=XXX

(obviously replacing XXX with valid values -- note, staging only for now)

You'll get back a JSON response.  If it's empty, you're all good (no errors).  Look for the email containing the link to "activate" your subscription.  Click on the link, and, assuming everything is fine, you should get  a message saying your subscription has been activated and a link to goto the Manage Notifications page.

**Comment by jywsn** [comment]
note to self:  take out dumb debugging code

**Comment by jywsn** [comment]
Ok, all the functionality for this stuff should be done.  All that's left is styling issues (#62 #63) and #61, so I'm closing this.
