### ISSUE TITLE
AJAX for sponsor filters

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#50]

**Comment by scott2b** [comment]
@hbillings clarify. Thanks

**Comment by hbillings** [comment]
I didn't take notes on this, because I agreed to enter tix at the end of the meeting. Someone else?

**Comment by jywsn** [comment]
Front-end needs to compile a list of Matter IDs, which would be sent to the back-end, which would return a list of sponsors with a count of matching matters (per sponsor).  So there is the front-end part (the code that makes the call and then deals with the returned data) and the back-end part.  

The front-end part is mixed up with however you want to implement the other post-search facets.  You should stub out the front-end ajax call, and then I can hook it into the back-end.  

Or if you want to do it some other way, that's fine, but then you need to add more detail on what you want.

**Comment by scott2b** [comment]
This feels next-iteration to me. There is too much of a backlog of issues right now to consider all of this a single iteration. The question then is, is this a pre-release requirement? If so, we should break the current release cycle into two separate iterations before the public/tribune release milestone 0.1.

**Comment by scott2b** [comment]
Closing for now. Filtering to be revisited.
