### ISSUE TITLE
Build list of available filter/facet values

### ISSUE THREAD

**Issue by hbillings** [NUKnightLab/cityhallmonitor#55]
We talked about the dangers of hardcoding filter/facet values, so we need to figure out how we're going to populate these.

**Comment by jywsn** [comment]
Are we talking about things they can search by, or things they can filter by post-search?  If the latter, then the list of values would be built from the document metadata returned in the results from document clouds  The exception is the Sponsors, which would require an ajax call back to our server.

Or maybe I don't understand the question, in which case, please clarify.

**Comment by hbillings** [comment]
Both, I think. Even if the date range is the only pre-search filter, we'll probably want to populate that based on available matters. But I think what you're saying for post-search facets is right.

**Comment by hbillings** [comment]
I think we've got a clear enough issue on this to close.
